config/routes.rb
Rails.application.routes.draw do # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'homepages#index'
  resources :skills, only: %i[index show]
  resources :projects, only: %i[index show]
  resources :homepages, only: [:index]
  resources :resumes, only: [:index]
  resources :contacts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :projects_skills
  has_many :skills, through: :projects_skills
end

app/models/projects_skill.rb
class ProjectsSkill < ActiveRecord::Base
  belongs_to :project
  belongs_to :skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :projects_skills
  has_many :projects, through: :projects_skills
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index; end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
    @projects = Project.all.includes(:skills).to_a
    @skills = Skill.all.includes(:projects).to_a
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @slug_filter = params[:using]
    @projects = if @slug_filter.present?
                  Project.all.where(skills: { slug: @slug_filter }).includes(:skills).to_a
                else
                  Project.all.includes(:skills).to_a
                end
    @skills = Skill.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index; end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all.includes(:projects).to_a
  end

  def show
    @skill = Skill.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.haml
%h1
  Contact

app/views/homepages/index.haml
%section
  .hero
    .hero--inner-section
      %h1.hero--text.-large
        Welcome!
      %h2.hero--text.-small
        My name is Draigan Le Febvre and I'm a self taught web developer.

      = link_to "/projects.html", class: "btn" do
        %span.btn--text
          Projects
      = link_to "https://github.com/draigan", class: "btn", target: "_blank", rel: "noopener" do 
        %span.btn--text
          Github
%section
  .practice>
    .practice--inner-section
      %h1.practice--header-test
        Why Hire Me?

      .practice--box-container
        .practice--box-sub-container
          .practice--box
            = image_tag "practice/heart.svg", class:"practice--image", alt:"Heart Symbol" 
            %h2.practice--inner-text
              I'm passionate about programming.

          .practice--box
            = image_tag "practice/clock.svg", class:"practice--image", alt:"Clock Symbol" 
            %h2.practice--inner-text
              I continue learning on my own time.</h2>

        .practice--box-sub-container
          .practice--box
            = image_tag "practice/directed.svg", class:"practice--image", alt:"Self Directed Symbol" 
            %h2.practice--inner-text
              I'm self directed and persistent.

          .practice--box
            = image_tag "practice/balloons.svg", class:"practice--image", alt:"Balloons Symbol" 
            %h2.practice--inner-text
              Fun at parties.


%section

  .project-wrapper
    .project-wrapper--header
      Relevant Projects

    .project-wrapper--inner-section
      - @projects.filter { |p| p.featured }.each do |p| 
        = render 'projects/project',  project: p  

    .project-wrapper--footer
      = link_to "/projects.html", class:"project--view-more" do
        View All Projects

%section

  .skill-wrapper
    .skill-wrapper--header
      Relevant Skills
    .skill-wrapper--inner-section

      - @skills.select { |s| s.featured }.each do |s| 
        = render 'skills/skill', skill: s, bem_modifier_skill_description: ""  

    .skill-wrapper--footer
      = link_to "/skills.html", class:"project--view-more" do
        View All Skills

app/views/layouts/application.haml
<!DOCTYPE html>
%html(lang="en")

  %head
    -# - if content_for? :open_graph
    -#   = yield_content :open_graph
    -# - else
    -#   %meta{content: current_page.data.description, name: "og:description"}
    -#   %meta{content: current_page.data.og_title, property: "og:title"}
    -#   %meta{content: current_page.data.og_url, property: "og:url"}
    -#   %meta{content: current_page.data.og_image, property: "og:image"}
    -#   %meta{content: current_page.data.og_type, property: "og:type"}

    %meta(charset="UTF-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=edge")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")


    -# = favicon_tag "favicon.ico"

    -# %title
    -#   = current_page.data.title 


    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    -# = stylesheet_link_tag "/assets/unpoly/unpoly" 
    -# = stylesheet_link_tag "normalize" 
    -# = stylesheet_link_tag "styles" 
    -# = stylesheet_link_tag "/assets/sudoku/sudoku" 
    -# = bem_blocks
    -# = javascript_include_tag "/assets/unpoly/unpoly", defer: true, type: "module"
    -# = javascript_include_tag "unpoly_config", defer: true, type: "module"
    -# = unpoly_compilers
  %body
    .layout
      .layout--header
        %header.header
          %nav.header--inner-section
            = link_to "/index.html" do 
              %h1 Draigan Le Febvre
            .header--menu
              .menu(up-nav)
                %ul.menu--ul
                  %li
                    = link_to "home", root_path, 'up-layer': "root"
                  %li
                    = link_to "projects", projects_path,'up-layer': "root", 'up-alias': "/projects/*"
                  %li
                    = link_to "resume", resumes_path, 'up-layer': "root"
                  %li
                    = link_to "tech & skills", skills_path, 'up-layer': "root"
                  %li
                    = link_to "contact", contacts_path, 'up-layer': "root"
                  %li
                    = link_to "https://github.com/draigan", class:"menu--icon-link", target:"_blank", rel:"noopener" do  
                      = image_tag "GitHub.png", class:"menu--icon", alt:"github" 


             
            = link_to root_path, class:"menu--hamburger-link", :'up-layer' => "new drawer", :'up-target' => ".menu--ul"  do 
              = image_tag "bars.svg", class:"menu--hamburger-image", alt:"Navigation" 


      %main.layout--main
        = yield 
      .layout--footer
        %footer.footer
          .footer--inner-section
            %span.footer--copyright
              © Copyright 2022</span>

app/views/projects/_project.haml
.project
  .project--image
    = link_to project do
      = image_tag project.image, alt: project.alt


  %h2.project--heading
    = project.title  

  %p.project--description
    = project.description 

  .project--skills-wrapper
    - project.skills.each do |skill|
      = link_to skill  do 
        = image_tag skill.image, class: "project--skill-image", alt: skill.alt


  .project--buttons
    - if project.custom_content
      = link_to project,  :class => "btn -black", :'up-layer' => "new", :'up-target' => ".project-view--custom-content"  do 
        %span.btn--text
          Live View

    = link_to project.github_url, class:"btn -black", target: "_blank", rel: "noopener" do 

      %span.btn--text
        Github

app/views/projects/custom_content/_calculator.html.haml
%h1
  = project.title

app/views/projects/custom_content/_chess.html.haml
%h1
  = project.title

app/views/projects/custom_content/_pass_generator.html.haml
%h1
  = project.title

app/views/projects/custom_content/_sudoku.html.haml
.sudoku(sudoku)

app/views/projects/index.haml
%section
  .project-page--title
    %h1
      - if @slug_filter != nil
        = "Projects Using"
        = @slug_filter
      - else
        = "All Projects"
  .project-page-inner-section
    .project-page--left-column
      - @projects.each do |p| 
        = render 'project',  project: p  

    .project-page--right-column
      %h5
        Filter By Skill
      %ul(up-nav)
        %li
          = link_to projects_path, :'up-history' => true, :'up-target' => ".project-page--left-column .project-page--title" do
            All projects 
        - @skills.sort_by { |skill| skill.name }.each do |s| 
          - if s.projects.size > 0
            %li
              = link_to projects_path(using:s.slug), :'up-history' => true, :'up-target' => ".project-page--left-column .project-page--title" do
                = "#{s.name}"

app/views/projects/show.haml
.project-view
  %h1.project-view-title= @project.title
  
  %span.project-view--date  
    = "Created At: #{@project.created_at} - Updated At:" 

    - if @project.updated_at.nil? 
      =  "Ongoing"
    - else 
      = @project.updated_at 

  %p.project-view--description
    = @project.description  

  .project-view--featured-image-wrapper
    = image_tag @project.image, class: "project-view--featured-image", alt: @project.alt


  %p.project-view--long-description= @project.long_description 
  = link_to @project.github_url, class:"btn -black", target:"_blank", rel:"noopener" do 
    %span.btn--text
      Github

  .project-view--custom-content
    - if @project.custom_content
      = render "projects/custom_content/#{@project.slug}" 

app/views/resumes/index.haml
%h1
  Resume

app/views/skills/_skill.haml
.skill{class: bem_modifier_skill_description}
  .skill--image
    = link_to skill do
      = image_tag skill.image, class: "skill--image", alt: skill.alt

  %h2.skill--heading
    = skill.name  

  %p.skill--description
    = skill.description 


  .skill--buttons
    = link_to skill, class:"btn -black" do 
      %span.btn--text
        Explore
    - if skill.projects.size > 0 
      = link_to "/projects/using/#{skill.slug}.html", 'up-layer':"new", 'up-target': ".project-page--left-column", class:"btn -black" do 
        %span.btn--text
          = skill.projects.size 
          - if skill.projects.size != 1
            = "projects"
          - else
            = "project"

app/views/skills/index.haml
%h1 Tech & Skills

.skill-wrapper
  .skill-wrapper--inner-section.-with-description
    - @skills.each do |s| 
      = render('skill',   skill: s, bem_modifier_skill_description: "-with-description" ) 

app/views/skills/show.haml
.skill-view
  %h1.skill-view--title= @skill.name 

  %p.skill-view--description
    = @skill.description  

  %p.skill-view--long-description
    = @skill.long_description 

  .skill-view--featured-image-wrapper
    = link_to projects_path(using: @skill.slug) do
      = image_tag @skill.image, class: "skill-view--featured-image", alt: @skill.alt